from enum import Enum


class Kind(Enum):
    KIND_2 = 'Đọc nghĩa và chọn ảnh - từ - phiên âm'
    KIND_3 = 'Nghe - đọc câu và chọn nghĩa'
    KIND_4 = 'Nghe - đọc câu và ghép nghĩa'
    KIND_5 = 'Nghe - đọc câu trả lời và chọn câu hỏi'
    KIND_6 = 'Nghe - đọc câu trả lời và ghép câu hỏi'
    KIND_7 = 'Nghe - đọc câu hỏi và chọn câu trả lời'
    KIND_8 = 'Nghe - đọc câu hỏi và ghép câu trả lời'
    KIND_9 = 'Nghe và chọn từ - phiên âm'
    KIND_10 = 'Nghe và ghép từ thành câu'
    KIND_11 = 'Nghe - đọc phiên âm và viết từ theo nét có sẵn (1 từ)'
    KIND_12 = 'Nghe - đọc phiên âm và viết từ theo nét có sẵn (nhiều từ)'
    KIND_13 = 'Nghe - đọc nghĩa và chọn câu'
    KIND_14 = 'Nghe - đọc nghĩa và ghép từ thành câu'
    KIND_15 = 'Nghe và chọn nghĩa'
    KIND_16 = 'Chọn hình phù hợp với đoạn ghi âm'
    KIND_17 = 'Đọc nghĩa - Xem ảnh và ghép chữ cái - phiên âm'
    KIND_18 = 'Đọc câu - phiên âm và chọn từ điền vào chỗ trống'
    KIND_19 = 'Đọc từ - phiên âm và chọn chỗ trống phù hợp'
    KIND_20 = 'Đọc nghĩa và chọn từ - phiên âm'
    KIND_21 = 'Đọc câu và bỏ từ hoặc cụm từ thừa'
    KIND_22 = 'Đọc nghĩa và ghép từ thành câu'
    KIND_23 = 'Nghe và nói lại'
    KIND_24 = 'Nghe - đọc từ (câu) và nói lại'
